name = "GaussianSSF"
uuid = "555e6017-eccf-45cb-b1a5-830490d56c85"
authors = ["ngedwin <ngedwin98@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
FFTW = "1.7.1"
